---
kind: pipeline
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: yapf
  image: python:3.9
  commands:
  - git fetch -tq
  - pip install poetry poetry-dynamic-versioning -qq
  - poetry install -q
  - poetry run yapf -dr ./corenetworks
  environment:
    PY_COLORS: 1

- name: flake8
  image: python:3.9
  commands:
  - git fetch -tq
  - pip install poetry poetry-dynamic-versioning -qq
  - poetry install -q
  - poetry run flake8 ./corenetworks
  environment:
    PY_COLORS: 1

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: python:3.9
  commands:
  - git fetch -tq

- name: python36-pytest
  image: python:3.6
  commands:
  - pip install poetry poetry-dynamic-versioning -qq
  - poetry install -q
  - poetry run pytest
  - poetry version
  environment:
    PY_COLORS: 1
  depends_on:
  - fetch

- name: python37-pytest
  image: python:3.7
  commands:
  - pip install poetry poetry-dynamic-versioning -qq
  - poetry install -q
  - poetry run pytest
  - poetry version
  environment:
    PY_COLORS: 1
  depends_on:
  - fetch

- name: python38-pytest
  image: python:3.8
  commands:
  - pip install poetry poetry-dynamic-versioning -qq
  - poetry install -q
  - poetry run pytest
  - poetry version
  environment:
    PY_COLORS: 1
  depends_on:
  - fetch

- name: python39-pytest
  image: python:3.9
  commands:
  - pip install poetry poetry-dynamic-versioning -qq
  - poetry install -q
  - poetry run pytest
  - poetry version
  environment:
    PY_COLORS: 1
  depends_on:
  - fetch

- name: codecov
  image: python:3.9
  commands:
  - pip install codecov -qq
  - codecov --required -X gcov
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
    PY_COLORS: 1
  depends_on:
  - python36-pytest
  - python37-pytest
  - python38-pytest
  - python39-pytest

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**

depends_on:
- lint

---
kind: pipeline
name: security

platform:
  os: linux
  arch: amd64

steps:
- name: bandit
  image: python:3.9
  commands:
  - git fetch -tq
  - pip install poetry poetry-dynamic-versioning -qq
  - poetry install -q
  - poetry run bandit -r ./corenetworks -x ./corenetworks/test
  environment:
    PY_COLORS: 1

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**

depends_on:
- test

---
kind: pipeline
name: build-package

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: python:3.9
  commands:
  - git fetch -tq
  - pip install poetry poetry-dynamic-versioning -qq
  - poetry build
  environment:
    SETUPTOOLS_SCM_PRETEND_VERSION: ${DRONE_TAG##v}

- name: checksum
  image: alpine
  commands:
  - cd dist/ && sha256sum * > ../sha256sum.txt

- name: publish-github
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - dist/*
    - sha256sum.txt
    note: CHANGELOG.md
    overwrite: true
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/**

- name: publish-pypi
  image: python:3.9
  commands:
  - git fetch -tq
  - pip install poetry poetry-dynamic-versioning -qq
  - poetry publish -n
  environment:
    POETRY_HTTP_BASIC_PYPI_PASSWORD:
      from_secret: pypi_password
    POETRY_HTTP_BASIC_PYPI_USERNAME:
      from_secret: pypi_username
  when:
    ref:
    - refs/tags/**

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**

depends_on:
- security

---
kind: pipeline
name: docs

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: generate
  image: python:3.9
  commands:
  - git fetch -tq
  - pip install poetry poetry-dynamic-versioning -qq
  - poetry install
  - make doc

- name: markdownlint
  image: thegeeklab/markdownlint-cli
  commands:
  - markdownlint 'docs/content/**/*.md' 'README.md' 'CONTRIBUTING.md' -p .gitignore

- name: spellcheck
  image: node:lts-alpine
  commands:
  - npm install -g spellchecker-cli
  - spellchecker --files 'docs/content/**/*.md' 'README.md' -d .dictionary -p spell indefinite-article syntax-urls --no-suggestions
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error

- name: testbuild
  image: klakegg/hugo:0.74.3-ext-alpine
  commands:
  - hugo-official -s docs/ -b http://localhost/

- name: link-validation
  image: thegeeklab/link-validator
  commands:
  - link-validator -ro
  environment:
    LINK_VALIDATOR_BASE_DIR: docs/public

- name: build
  image: klakegg/hugo:0.74.3-ext-alpine
  commands:
  - hugo-official -s docs/

- name: beautify
  image: node:lts-alpine
  commands:
  - npm install -g js-beautify
  - html-beautify -r -f 'docs/public/**/*.html'
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error

- name: publish
  image: plugins/s3-sync
  settings:
    access_key:
      from_secret: s3_access_key
    bucket: geekdocs
    delete: true
    endpoint: https://sp.rknet.org
    path_style: true
    secret_key:
      from_secret: s3_secret_access_key
    source: docs/public/
    strip_prefix: docs/public/
    target: /${DRONE_REPO_NAME}
  when:
    ref:
    - refs/heads/main
    - refs/tags/**

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**

depends_on:
- build-package

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: matrix
  image: plugins/matrix
  settings:
    homeserver:
      from_secret: matrix_homeserver
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    template: "Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message: {{ build.message }}"
    username:
      from_secret: matrix_username
  when:
    status:
    - success
    - failure

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- docs

---
kind: signature
hmac: 2a8711f166f19c03f78909ab06c72ad8fd8e4c4a5689208a494f84268ee26ebc

...
