---
kind: pipeline
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: flake8
  image: python:3.8
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - flake8 ./corenetworks
  environment:
    PY_COLORS: 1

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: python27-ansible
  image: python:2.7
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - pytest corenetworks/tests/ --cov=corenetworks/ --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python35-ansible
  image: python:3.5
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - pytest corenetworks/tests/ --cov=corenetworks/ --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python36-ansible
  image: python:3.6
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - pytest corenetworks/tests/ --cov=corenetworks/ --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python37-ansible
  image: python:3.7
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - pytest corenetworks/tests/ --cov=corenetworks/ --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python38-ansible
  image: python:3.8
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - pytest corenetworks/tests/ --cov=corenetworks/ --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: codecov
  image: python:3.8
  commands:
  - pip install codecov
  - codecov --required
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
    PY_COLORS: 1

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- dependencies

---
kind: pipeline
name: security

platform:
  os: linux
  arch: amd64

steps:
- name: bandit
  image: python:3.8
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - bandit -r ./corenetworks -x ./corenetworks/tests
  environment:
    PY_COLORS: 1

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- test

---
kind: pipeline
name: build-package

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: python:3.8
  commands:
  - python setup.py sdist bdist_wheel
  environment:
    SETUPTOOLS_SCM_PRETEND_VERSION: ${DRONE_TAG##v}

- name: checksum
  image: alpine
  commands:
  - cd dist/ && sha256sum * > ../sha256sum.txt

- name: publish-github
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - dist/*
    - sha256sum.txt
    note: CHANGELOG.md
    overwrite: true
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/**

- name: publish-pypi
  image: plugins/pypi
  settings:
    password:
      from_secret: pypi_password
    repository: https://upload.pypi.org/legacy/
    skip_build: true
    username:
      from_secret: pypi_username
  when:
    ref:
    - refs/tags/**

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- security

---
kind: pipeline
name: docs

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: assets
  image: byrnedo/alpine-curl
  commands:
  - mkdir -p docs/themes/hugo-geekdoc/
  - curl -L https://github.com/xoxys/hugo-geekdoc/releases/latest/download/hugo-geekdoc.tar.gz | tar -xz -C docs/themes/hugo-geekdoc/ --strip-components=1

- name: test
  image: klakegg/hugo:0.59.1-ext-alpine
  commands:
  - cd docs/ && hugo-official

- name: freeze
  image: appleboy/drone-ssh:1.5.5
  settings:
    host:
      from_secret: ssh_host
    key:
      from_secret: ssh_key
    script:
    - cp -R /var/www/virtual/geeklab/html/corenetworks.geekdocs.de/ /var/www/virtual/geeklab/html/corenetworks_freeze/
    - ln -sfn /var/www/virtual/geeklab/html/corenetworks_freeze /var/www/virtual/geeklab/corenetworks.geekdocs.de
    username:
      from_secret: ssh_username

- name: publish
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    key:
      from_secret: ssh_key
    rm: true
    source: docs/public/*
    strip_components: 2
    target: /var/www/virtual/geeklab/html/corenetworks.geekdocs.de/
    username:
      from_secret: ssh_username

- name: cleanup
  image: appleboy/drone-ssh:1.5.5
  settings:
    host:
      from_secret: ssh_host
    key:
      from_secret: ssh_key
    script:
    - ln -sfn /var/www/virtual/geeklab/html/corenetworks.geekdocs.de /var/www/virtual/geeklab/corenetworks.geekdocs.de
    - rm -rf /var/www/virtual/geeklab/html/corenetworks_freeze/
    username:
      from_secret: ssh_username

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**

depends_on:
- build-package
- build-container-amd64
- build-container-arm64
- build-container-arm

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: matrix
  image: plugins/matrix
  settings:
    homeserver:
      from_secret: matrix_homeserver
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    template: "Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message: {{ build.message }}"
    username:
      from_secret: matrix_username
  when:
    status:
    - success
    - failure

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- docs

---
kind: signature
hmac: e0cd32befb8e01ec9cb6bd0e7bc032fe0816bcda9e16d89f37789a7db9ba9b82

...
