---
kind: pipeline
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: flake8
  image: python:3.8
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - flake8 ./corenetworks
  environment:
    PY_COLORS: 1

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: python27-pytest
  image: python:2.7
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - pytest corenetworks --cov=corenetworks --cov-append --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python35-pytest
  image: python:3.5
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - pytest corenetworks --cov=corenetworks --cov-append --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python36-pytest
  image: python:3.6
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - pytest corenetworks --cov=corenetworks --cov-append --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python37-pytest
  image: python:3.7
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - pytest corenetworks --cov=corenetworks --cov-append --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python38-pytest
  image: python:3.8
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - pytest corenetworks --cov=corenetworks --cov-append --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: codecov
  image: python:3.8
  commands:
  - pip install codecov -qq
  - codecov --required -X gcov
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
    PY_COLORS: 1
  depends_on:
  - python27-pytest
  - python35-pytest
  - python36-pytest
  - python37-pytest
  - python38-pytest

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- lint

---
kind: pipeline
name: security

platform:
  os: linux
  arch: amd64

steps:
- name: bandit
  image: python:3.8
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - bandit -r ./corenetworks -x ./corenetworks/test
  environment:
    PY_COLORS: 1

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- test

---
kind: pipeline
name: build-package

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: python:3.8
  commands:
  - python setup.py sdist bdist_wheel
  environment:
    SETUPTOOLS_SCM_PRETEND_VERSION: ${DRONE_TAG##v}

- name: checksum
  image: alpine
  commands:
  - cd dist/ && sha256sum * > ../sha256sum.txt

- name: publish-github
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - dist/*
    - sha256sum.txt
    note: CHANGELOG.md
    overwrite: true
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/**

- name: publish-pypi
  image: plugins/pypi
  settings:
    password:
      from_secret: pypi_password
    repository: https://upload.pypi.org/legacy/
    skip_build: true
    username:
      from_secret: pypi_username
  when:
    ref:
    - refs/tags/**

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- security

---
kind: pipeline
name: docs

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: generate
  image: python:3.8
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - make doc

- name: markdownlint
  image: node:lts-alpine
  commands:
  - npm install -g markdownlint-cli
  - markdownlint 'docs/content/**/*.md' 'README.md' -p .gitignore
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error

- name: spellcheck
  image: node:lts-alpine
  commands:
  - npm install -g spellchecker-cli
  - spellchecker --files 'docs/content/**/*.md' 'README.md' -d .dictionary -p spell indefinite-article syntax-urls --no-suggestions
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error

- name: testbuild
  image: klakegg/hugo:0.74.3-ext-alpine
  commands:
  - hugo-official -s docs/ -b http://localhost/

- name: link-validation
  image: thegeeklab/link-validator
  commands:
  - link-validator -ro
  environment:
    LINK_VALIDATOR_BASE_DIR: docs/public

- name: build
  image: klakegg/hugo:0.74.3-ext-alpine
  commands:
  - hugo-official -s docs/

- name: beautify
  image: node:lts-alpine
  commands:
  - npm install -g js-beautify
  - html-beautify -r -f 'docs/public/**/*.html'
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error

- name: publish
  image: plugins/s3-sync
  settings:
    access_key:
      from_secret: s3_access_key
    bucket: geekdocs
    delete: true
    endpoint: https://sp.rknet.org
    path_style: true
    secret_key:
      from_secret: s3_secret_access_key
    source: docs/public/
    strip_prefix: docs/public/
    target: /${DRONE_REPO_NAME}
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- build-package

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: matrix
  image: plugins/matrix
  settings:
    homeserver:
      from_secret: matrix_homeserver
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    template: "Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message: {{ build.message }}"
    username:
      from_secret: matrix_username
  when:
    status:
    - success
    - failure

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- docs

---
kind: signature
hmac: 36e94ce280e52e18c290f7ee728d68f2353570df5e5327f649668af22f0005ea

...
