---
baseURL: https://corenetworks.geekdocs.de/
title: corenetworks
theme: hugo-geekdoc

disablePathToLower: true
enableGitInfo: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

params:
  geekdocMenuBundle: true
  geekdocToC: 3

  geekdocRepo: https://github.com/xoxys/corenetworks
  geekdocEditPath: edit/master/docs/content

  geekdocDateFormat: "Jan 2, 2006"
  geekdocSearch: true

  geekdocLegalNotice: https://geeklabor.de/legal-notice/#impressum
  geekdocPrivacyPolicy: https://geeklabor.de/legal-notice/#datenschutzerkl%C3%A4rung

  geekdocAnchorLeft: true
